# Generated by Django 3.1.4 on 2020-12-11 03:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/pics'), upload_to=''),
        ),
    ]
